FROM golang:1.19 as builder

RUN set -x && apt-get update -y && DEBIAN_FRONTEND=noninteractive apt-get install -y \
    ca-certificates wget jq procps curl vim && \
    rm -rf /var/lib/apt/lists/*

WORKDIR /plugin

COPY go.mod go.mod
COPY go.sum go.sum

RUN go mod download

ENTRYPOINT ["sleep", "infinity"]