name: CI

on:
  - push
  - pull_request
  - workflow_dispatch

jobs:
  ci:
    runs-on: ${{ matrix.os }}
    strategy:
      max-parallel: 1
      matrix:
        os:
          - ubuntu-latest
        go-version:
          - "1.19"
    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: set up go ${{ matrix.go-version }}
        uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go-version }}
      - name: lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.50
          args: --timeout 5m
      - name: install gotestsum
        run: go install gotest.tools/gotestsum@latest
      - name: tests
        run: make test-race
